run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - funlen
    - dupl
    - revive
    - paralleltest # goleak does not support t.Parallel()

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosimple:
    checks: ["all"]
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  staticcheck:
    checks: ["all"]
  decorder:
    ignore-underscore-vars: false
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: false
    disable-type-dec-num-check: false
    disable-const-dec-num-check: false
    disable-var-dec-num-check: false
  dogsled:
    max-blank-identifiers: 1
  errchkjson:
    report-no-exported: true
  gocognit:
    min-complexity: 10
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    settings:
      captLocal:
        paramsOnly: false
      hugeParam:
        sizeThreshold: 40
  gofumpt:
    extra-rules: true
  gomoddirectives:
    replace-local: true
  gosec:
    config:
      global:
        audit: true
  grouper:
    const-require-single-const: true
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: true
    type-require-single-type: true
    type-require-grouping: false
    var-require-single-var: true
    var-require-grouping: false
  varnamelen:
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
  whitespace:
    multi-if: true
    multi-func: true
  nonamedreturns:
    report-error-in-defer: true
  depguard:
    rules:
      main:
        files:
          - "$all"
          - "!$test"
        allow:
          - "$gostd"
