version: "2"

linters:
  default: all
  disable:
    - paralleltest
  settings:
    gomoddirectives:
      replace-local: true

formatters:
  enable:
    - gci
    - gofumpt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: false

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  tests: false