run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - funlen
    - dupl
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosimple:
    checks: ["all"]
  govet:
    check-shadowing: true
    enable-all: true
  staticcheck:
    checks: ["all"]
  decorder:
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: false
  dogsled:
    max-blank-identifiers: 1
  errchkjson:
    report-no-exported: true
  exhaustive:
    check-generated: true
    default-signifies-exhaustive: true
  gci:
    no-inline-comments: true
    no-prefix-comments: true
  gocognit:
    min-complexity: 10
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
    settings:
      captLocal:
        paramsOnly: false
      hugeParam:
        sizeThreshold: 40
      truncateCmp:
        skipArchDependent: false
      underef:
        skipRecvDeref: false
  gofumpt:
    extra-rules: true
  gomoddirectives:
    replace-local: true
  gosec:
    config:
      global:
        audit: true
  grouper:
    const-require-single-const: true
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: false
    type-require-single-type: true
    type-require-grouping: false
    var-require-single-var: true
    var-require-grouping: false
  tenv:
    all: true
  varnamelen:
    max-distance: 20
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
  whitespace:
    multi-if: true
    multi-func: true
  nonamedresult:
    report-error-in-defer: true
  depguard:
    rules:
      main:
        files:
          - "$all"
          - "!$test"
        allow:
          - "$gostd"
