name: update_deps
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  update_deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: 'oldstable'
          check-latest: true
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Locally update dependencies
        run: go get -u ./... && go mod tidy
      - name: Commit changes and create PR if we have any changes
        run: bash .github/update_deps.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: fix/autoupdate_dependencies
          REPO_NAME: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
